import Carousel from 'better-react-carousel'

export const Gallery: React.FC = () => (
  <Carousel cols={5} rows={2} gap={10} loop autoplay showDots hideArrow>
    <Carousel.Item>
      <img
        width="100%"
        src="https://picsum.photos/800/600?random=1"
        alt="asd"
      />
    </Carousel.Item>
    <Carousel.Item>
      <img
        width="100%"
        src="https://picsum.photos/800/600?random=2"
        alt="asd"
      />
    </Carousel.Item>
    <Carousel.Item>
      <img
        width="100%"
        src="https://picsum.photos/800/600?random=3"
        alt="asd"
      />
    </Carousel.Item>
    <Carousel.Item>
      <img
        width="100%"
        src="https://picsum.photos/800/600?random=4"
        alt="asd"
      />
    </Carousel.Item>
    <Carousel.Item>
      <img
        width="100%"
        src="https://picsum.photos/800/600?random=5"
        alt="asd"
      />
    </Carousel.Item>
    <Carousel.Item>
      <img
        width="100%"
        src="https://picsum.photos/800/600?random=6"
        alt="asd"
      />
    </Carousel.Item>
    <Carousel.Item>
      <img
        width="100%"
        src="https://picsum.photos/800/600?random=7"
        alt="asd"
      />
    </Carousel.Item>
    <Carousel.Item>
      <img
        width="100%"
        src="https://picsum.photos/800/600?random=8"
        alt="asd"
      />
    </Carousel.Item>
    <Carousel.Item>
      <img
        width="100%"
        src="https://picsum.photos/800/600?random=9"
        alt="asd"
      />
    </Carousel.Item>
    <Carousel.Item>
      <img
        width="100%"
        src="https://picsum.photos/800/600?random=10"
        alt="asd"
      />
    </Carousel.Item>
  </Carousel>
)
